---
roles:
  # Install a role from Ansible Galaxy.
  - name: geerlingguy.java
    version: 2.1.0

collections:
  # Install a collection from Ansible Galaxy.
  - name: geerlingguy.php_roles
    version: 0.9.3
  - name: davidban77.gns3
    version: 1.2.2
